# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: publish
      run: dotnet publish --no-restore --output out
      
    - name: Upload artifact for Selenium Test
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Publish artifact
        path: out
          
  deploy_test:
    runs-on: windows-latest
    needs: build
    steps:
        
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: Publish artifact
        
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test LibreriaABC_Selenium_Test.dll --verbosity normal --logger "trx;LogFileName=test-results.trx" || true
    
    - uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: DotNET Tests
        path: 'TestResults/test-results.trx'
        reporter: dotnet-trx
        fail-on-error: true
        token: ${{ secrets.GITHUB_TOKEN }}
  

  
